#!/usr/bin/env bash
# Description: pulling some useful or common Docker images from docker registry.

command -v docker > /dev/null || {
    echo -e "\e[1;31mERROR: docker command not found, please install docker use https://get.docker.com/ \e[0m" 2>&1
    exit 1
}

if ! docker info &> /dev/null; then
    echo -e "\e[1;31mERROR: got permission denied while using docker, please check it.\e[0m" 2>&1
    exit 1
fi

images="centos:7.4.1708 centos:6.9 ubuntu:16.04 debian:jessie intelpython/intelpython2_full:latest"

for image in $images; do
    echo -e "\e[1;32mINFO: pull $image image ...\e[0m" 2>&1
    docker pull "$image" > /dev/null || echo -e "\e[1;31mERROR: cannot pull $image image ...\e[0m" 2>&1
done
