# CentOS 7.4 SSH docker + SSH X11 Forwarding
# Login info: root / rootroot

FROM centos:7.4.1708

RUN yum install -y epel-release && yum install -y openssh-server xorg-x11-xauth dbus libcanberra-gtk3 PackageKit-gtk3-module wqy-zenhei-fonts \
    && dbus-uuidgen > /var/lib/dbus/machine-id && echo -e "rootroot\nrootroot" | passwd --stdin root

# https://github.com/CentOS/CentOS-Dockerfiles/blob/master/ssh/centos7/Dockerfile
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' && sed -i "/#X11UseLocalhost/c X11UseLocalhost no" /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
