# CentOS 7.4 SSH docker + SSH X11 Forwarding
# Login info: root / rootroot

FROM centos:7.4.1708

RUN yum install -y epel-release && yum install -y sudo pssh openssh-server xorg-x11-xauth dbus libcanberra-gtk3 libcanberra-gtk2 \
    PackageKit-gtk3-module wqy-zenhei-fonts && dbus-uuidgen > /var/lib/dbus/machine-id && echo "root:rootroot" | chpasswd

# About default ssh-key generate, a better way: ssh-keygen -A
RUN yes | ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' > /dev/null && yes | ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' > /dev/null \
    && ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N '' > /dev/null && sed -i "/#X11UseLocalhost/c X11UseLocalhost no" /etc/ssh/sshd_config \
    # http://www.ducea.com/2006/06/18/linux-tips-password-usage-in-sudo-passwd-nopasswd/
    && echo "Defaults   !authenticate" >> /etc/sudoers && echo "ALL     ALL=(ALL)       NOPASSWD:ALL" >> /etc/sudoers

EXPOSE 22

CMD ["/usr/bin/sudo", "/usr/sbin/sshd", "-D"]
