#!/usr/bin/env bash
# Description: it will delete all incomplete docker images.

command -v docker > /dev/null || {
    echo "ERROR: docker command not found, please install docker use https://get.docker.com/ "
    exit 1
}

if ! docker info &> /dev/null; then
    echo "ERROR: got permission denied while using docker, please check it."
    exit 1
fi

image_commit=$(docker images | grep -w "none" | awk '{print $3}')

if [[ -z "$image_commit" ]]; then
    echo "INFO: no appropriate docker images to delete."
else
    while read -r commit; do
        docker rmi -f "$commit"
    done <<< "$image_commit"
fi
